# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

os:
  - linux
  - osx
# add back osx later with clean solution for openmp/rcpparmadillo

r: release

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE
    - ASAN="-fsanitize=address -fno-omit-frame-pointer"
    - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
    - HDF5_VERSION=1.12.0
    - HDF5_RELEASE_URL="https://support.hdfgroup.org/ftp/HDF5/releases"

before_install:
  - chmod +x travis_setup.sh
  - ./travis_setup.sh

  
warnings_are_errors: false
